### ISSUE TITLE
about the input of category

### ISSUE THREAD

**Issue by goryeon** [wuch15/IJCAI2019-NAML#9]
the input of category is in the form of one-hot or another?

**Comment by wuch15** [comment]
The category input is a discrete variable rather than a one-hot vector. The shape is (batch_size,1). Then the category variable will be converted into its embedding vector. It does not matter that you use the one-hot form, since you can add a dense layer (without bias) to achieve similar functions.

**Comment by goryeon** [comment]
> The category input is a discrete variable rather than a one-hot vector. The shape is (batch_size,1). Then the category variable will be converted into its embedding vector. It does not matter that you use the one-hot form, since you can add a dense layer (without bias) to achieve similar functions.

Thank you for your reply!
